base: 'http://example.com/'
baseVariants: {  }
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=1'
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: ''
    hreflang: 'de-DE'
    direction: ''
    flag: de
    languageId: '0'
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    map:
      /: 0
  TtProducts:
    type: Plugin
    routePath: '/products/{product}'
    namespace: tt_products
    requirements:
      product: '[\w].*'
    aspects:
      product:
        type: PersistedAliasMapper
        tableName: tt_products
        routeFieldName: slug
  TtProductsCategory:
    type: Plugin
    routePath: '/cat/{cat}'
    namespace: tt_products
    requirements:
      cat: '[\w].*'
    aspects:
      cat:
        type: PersistedAliasMapper
        tableName: tt_products_cat
        routeFieldName: slug
  TtProductsCategoryProduct:
    type: Plugin
    routePath: '/cat/{cat}/products/{product}'
    namespace: tt_products
    requirements:
      cat: '[\w].*'
      product: '[\w].*'
    aspects:
      cat:
        type: PersistedAliasMapper
        tableName: tt_products_cat
        routeFieldName: slug
      product:
        type: PersistedAliasMapper
        tableName: tt_products
        routeFieldName: slug
  TtProductsPagination:
    type: Plugin
    routePath: '/browsep/{pp}'
    namespace: tt_products
    requirements:
      pp: '[0-9]*'
    aspects:
      pp:
        type: StaticRangeMapper
        start: '0'
        end: '100'
  TtProductsProductsWithPagination:
    type: Plugin
    routePath: '/products/{product}/browsep/{pp}'
    namespace: tt_products
    requirements:
      pp: '[0-9]*'
      product: '[\w].*'
    aspects:
      product:
        type: PersistedAliasMapper
        tableName: tt_products
        routeFieldName: slug
      pp:
        type: StaticRangeMapper
        start: '0'
        end: '100'
  TtProductsCategoryPagination:
    type: Plugin
    routePath: '/cat/{cat}/browsep/{pp}'
    namespace: tt_products
    requirements:
      cat: '[\w].*'
      pp: '[0-9]*'
    aspects:
      cat:
        type: PersistedAliasMapper
        tableName: tt_products_cat
        routeFieldName: slug
      pp:
        type: StaticRangeMapper
        start: '0'
        end: '100'
  TtProductsOnlyBackPid:
    type: Plugin
    routePath: '/backPID/{backPID}'
    namespace: tt_products
    requirements:
      backPID: '[\w].*'
    aspects:
      backPID:
        type: PersistedPatternMapper
        tableName: pages
        routeFieldPattern: '^(?P<title>.+)$'
        routeFieldResult: '{title}'
  TtProductsBackPid:
    type: Plugin
    routePath: '/products/{product}/backPID/{backPID}'
    namespace: tt_products
    requirements:
      backPID: '[\w].*'
      product: '[\w].*'
    aspects:
      backPID:
        type: PersistedPatternMapper
        tableName: pages
        routeFieldPattern: '^(?P<title>.+)$'
        routeFieldResult: '{title}'
      product:
        type: PersistedAliasMapper
        tableName: tt_products
        routeFieldName: slug
  TtProductsSearchDetail:
    type: Plugin
    routePath: '/products/{product}/backPID/{backPID}/sword/{sword}'
    namespace: tt_products
    requirements:
      backPID: '[\w].*'
      product: '[\w].*'
    aspects:
      backPID:
        type: PersistedPatternMapper
        tableName: pages
        routeFieldPattern: '^(?P<title>.+)$'
        routeFieldResult: '{title}'
      product:
        type: PersistedAliasMapper
        tableName: tt_products
        routeFieldName: slug
  TtProductsWithPaginationAndBackPid:
    type: Plugin
    routePath: '/products/{product}/backPID/{backPID}/browsep/{pp}'
    namespace: tt_products
    requirements:
      backPID: '[\w].*'
      product: '[\w].*'
      pp: '[0-9]*'
    aspects:
      backPID:
        type: PersistedPatternMapper
        tableName: pages
        routeFieldPattern: '^(?P<title>.+)$'
        routeFieldResult: '{title}'
      product:
        type: PersistedAliasMapper
        tableName: tt_products
        routeFieldName: slug
      pp:
        type: StaticRangeMapper
        start: '0'
        end: '100'
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\nSitemap: https://www.example.com/sitemap.xml"
  -
    route: sitemap.xml
    type: uri
    source: 't3://page?uid=1&type=1533906435'
  -
    route: rss.xml
    type: uri
    source: 't3://page?uid=1194&type=103'
